package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.UUID;
import org.openapitools.model.Organisation;
import org.openapitools.model.Person;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * ReadCustomersDataCustomerInner
 */

@JsonIgnoreProperties(
  value = "CustomerType", // ignore manually set CustomerType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the CustomerType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "CustomerType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Organisation.class, name = "Organisation"),
  @JsonSubTypes.Type(value = Person.class, name = "Person")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-04-07T15:51:45.519635+01:00[Europe/London]")
public class ReadCustomersDataCustomerInner {

  private UUID customerId;

  private String customerType;

  private String firstName;

  private String name;

  /**
   * Default constructor
   * @deprecated Use {@link ReadCustomersDataCustomerInner#ReadCustomersDataCustomerInner(String)}
   */
  @Deprecated
  public ReadCustomersDataCustomerInner() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public ReadCustomersDataCustomerInner(String customerType) {
    this.customerType = customerType;
  }

  public ReadCustomersDataCustomerInner customerId(UUID customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Get customerId
   * @return customerId
  */
  @Valid 
  @Schema(name = "CustomerId", accessMode = Schema.AccessMode.READ_ONLY, requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("CustomerId")
  public UUID getCustomerId() {
    return customerId;
  }

  public void setCustomerId(UUID customerId) {
    this.customerId = customerId;
  }

  public ReadCustomersDataCustomerInner customerType(String customerType) {
    this.customerType = customerType;
    return this;
  }

  /**
   * Get customerType
   * @return customerType
  */
  @NotNull 
  @Schema(name = "CustomerType", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("CustomerType")
  public String getCustomerType() {
    return customerType;
  }

  public void setCustomerType(String customerType) {
    this.customerType = customerType;
  }

  public ReadCustomersDataCustomerInner firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
  */
  
  @Schema(name = "FirstName", example = "Ross Poldark", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("FirstName")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ReadCustomersDataCustomerInner name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
  */
  
  @Schema(name = "Name", example = "Wheal Leisure", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadCustomersDataCustomerInner readCustomersDataCustomerInner = (ReadCustomersDataCustomerInner) o;
    return Objects.equals(this.customerId, readCustomersDataCustomerInner.customerId) &&
        Objects.equals(this.customerType, readCustomersDataCustomerInner.customerType) &&
        Objects.equals(this.firstName, readCustomersDataCustomerInner.firstName) &&
        Objects.equals(this.name, readCustomersDataCustomerInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, customerType, firstName, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadCustomersDataCustomerInner {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

